import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('es');

  const translations: Record<Language, Record<string, string>> = {
    es: {
      // Header
      'header.home': 'Inicio',
      'header.about': 'Sobre Mí',
      'header.podcast': 'Podcast',
      'header.services': 'Servicios',
      'header.process': 'Proceso',
      'header.resources': 'Recursos',
      'header.testimonials': 'Testimonios',
      'header.faq': 'FAQ',
      'header.contact': 'Contacto',
      'header.cta': 'Agenda una asesoría',
      
      // Hero
      'hero.badge': 'Asesor Financiero Personal',
      'hero.title1': 'Tu aliado para',
      'hero.highlight': 'proteger y hacer crecer',
      'hero.title2': 'tu patrimonio familiar.',
      'hero.description': 'Te acompaño en tu camino hacia la libertad financiera con un enfoque educativo, transparente y 100% personalizado. Porque creo que las mejores decisiones se toman con conocimiento y confianza.',
      'hero.cta': 'Hablemos sobre tus objetivos financieros',
      'hero.services': 'Conoce cómo puedo ayudarte',
      'hero.clients': 'Clientes satisfechos',
      'hero.experience': 'Asesoría Internacional',
      'hero.commitment': 'Compromiso',
      'hero.visualName': 'Gregorio Leñero',
      'hero.visualTitle': 'Asesor Financiero Certificado',
      'hero.visualBadge': 'Certificado',
      'hero.floatCard1': 'Crecimiento Patrimonial',
      'hero.floatCard2': 'Protección Total',
      'hero.floatCard3': 'Metas Claras',
      
      // About Section
      'about.badge': 'Sobre Mí',
      'about.title': 'Construyendo resiliencia financiera con educación y acompañamiento humano.',
      'about.subtitle': 'Asesor Financiero en Canadá y EE. UU.',
      'about.subtitleDesc': 'Ayudo a personas, familias y negocios a construir resiliencia financiera y alcanzar su número de independencia financiera.',
      'about.intro': 'Soy Gregorio Leñero, asesor financiero con una misión clara: ayudarte a construir resiliencia financiera y alcanzar tu independencia económica. Mi enfoque va más allá de los números; creo firmemente que cada decisión financiera debe estar alineada con tus valores, sueños y metas de vida.',
      'about.bio': 'Con años de experiencia asesorando a familias y negocios en Norteamérica, he desarrollado una metodología centrada en la educación financiera y el acompañamiento humano. Mi objetivo es empoderarte con el conocimiento y las herramientas necesarias para que tomes decisiones inteligentes, protejas lo que has construido y hagas crecer tu patrimonio con confianza.',
      'about.mission': 'Mi misión es simple: empoderarte con el conocimiento y las herramientas necesarias para que tomes decisiones financieras inteligentes, protejas lo que has construido y hagas crecer tu patrimonio con confianza.',
      'about.approachTitle': 'Mi enfoque',
      'about.approachText': 'Creo que las decisiones financieras más importantes de la vida deben tomarse con claridad, educación y acompañamiento humano. Mi objetivo es ayudarte a entender tus opciones y construir una estrategia financiera alineada con tus metas personales, familiares o empresariales.',
      'about.certificationsTitle': 'Certificaciones',
      'about.certificationsText': 'Gregorio Leñero cuenta con certificaciones en British Columbia, Alberta y Ontario.',
      'about.certification': 'Asesor Certificado',
      'about.certificationDesc': 'Certificado en British Columbia, Alberta y Ontario.',
      'about.experience': 'Trayectoria Internacional',
      'about.experienceDesc': 'Experiencia comprobada ayudando a familias en Norteamérica.',
      'about.families': '500+ Familias',
      'about.familiesDesc': 'Confían en mí para su tranquilidad financiera.',
      'about.approach': 'Enfoque Humano',
      'about.approachDesc': 'Cada cliente es único, y mi asesoría se adapta a tus necesidades.',
      
      // Services
      'services.title': 'Nuestros Servicios',
      'services.subtitle': 'Soluciones financieras integrales diseñadas para cada etapa de tu vida',
      'services.insurance': 'Seguros',
      'services.insurance.desc': 'Te ayudamos a proteger lo que más quieres con soluciones de seguros de vida, gastos médicos y patrimonio.',
      'services.investments': 'Inversiones',
      'services.investments.desc': 'Administramos tu portafolio de inversiones con un enfoque profesional y diversificado.',
      'services.retirement': 'Retiro',
      'services.retirement.desc': 'Diseñamos estrategias personalizadas para que disfrutes de tu retiro con tranquilidad financiera.',
      'services.planning': 'Planeación financiera',
      'services.planning.desc': 'Te brindamos las herramientas y conocimientos para que tomes decisiones financieras informadas.',
      'services.protection': 'Protección patrimonial',
      'services.protection.desc': 'Protegemos tu patrimonio mediante estrategias legales y financieras.',
      'services.family': 'Asesoría familiar',
      'services.family.desc': 'Trabajamos con familias para alinear objetivos financieros y crear un legado sólido.',
      
      // Philosophy
      'philosophy.badge': 'Mi Filosofía',
      'philosophy.title': 'Detrás de cada número, hay una persona',
      'philosophy.description': 'Creo que la asesoría financiera va más allá de los números y las gráficas. Se trata de entender tus sueños, tus preocupaciones y tus metas. Por eso, pongo a las personas en el centro de todo lo que hago.',
      'philosophy.f1': 'Atención 100% personalizada y sin prisas',
      'philosophy.f2': 'Explicaciones claras, sin tecnicismos confusos',
      'philosophy.f3': 'Acompañamiento en cada etapa de tu vida financiera',
      'philosophy.f4': 'Transparencia total en recomendaciones y costos',
      'philosophy.f5': 'Relación de largo plazo, no venta única',
      
      // Process
      'process.title': 'Nuestro Proceso',
      'process.subtitle': 'Un camino claro y estructurado hacia tus metas financieras',
      'process.step1': 'Conversación inicial',
      'process.step1.desc': 'Nos conocemos y entendemos tu situación actual, tus metas y preocupaciones financieras.',
      'process.step2': 'Entendimiento de objetivos',
      'process.step2.desc': 'Analizamos a fondo tus necesidades, tu perfil de riesgo y tus expectativas de largo plazo.',
      'process.step3': 'Opciones personalizadas',
      'process.step3.desc': 'Diseñamos una propuesta adaptada específicamente a tu situación y objetivos.',
      'process.step4': 'Explicación clara',
      'process.step4.desc': 'Te explicamos cada detalle de la estrategia, resolviendo todas tus dudas sin prisas.',
      'process.step5': 'Implementación',
      'process.step5.desc': 'Ponemos en marcha el plan, acompañándote en cada paso del proceso.',
      'process.step6': 'Acompañamiento continuo',
      'process.step6.desc': 'Damos seguimiento constante y ajustamos la estrategia según sea necesario.',
      
      // Trust
      'trust.title': 'Confianza y Seguridad',
      'trust.subtitle': 'Tu patrimonio en manos de profesionales certificados',
      'trust.t1': 'Certificaciones en Canadá',
      'trust.t1.desc': 'Gregorio Leñero cuenta con certificaciones en British Columbia, Alberta y Ontario, lo que respalda su capacidad para asesorar a clientes en distintas provincias de Canadá.',
      'trust.t2': 'Trayectoria Internacional',
      'trust.t2.desc': 'Experiencia comprobada ayudando a familias en Norteamérica.',
      'trust.t3': 'Alianzas Sólidas',
      'trust.t3.desc': 'Trabajamos con las instituciones financieras más reconocidas.',
      'trust.t4': '500+ Familias',
      'trust.t4.desc': 'Más de 500 familias confían en nosotros para su tranquilidad financiera.',
      
      // Testimonials
      'testimonials.title': 'Lo Que Dicen Nuestros Clientes',
      'testimonials.subtitle': 'Historias reales de personas que confiaron en nosotros',
      'testimonials.t1Name': 'María González',
      'testimonials.t1Role': 'Empresaria',
      'testimonials.t1Content': 'Gregorio cambió completamente mi perspectiva sobre el dinero. Gracias a su asesoría, logré proteger a mi familia y hacer crecer mis inversiones de manera inteligente.',
      'testimonials.t2Name': 'Carlos Hernández',
      'testimonials.t2Role': 'Médico',
      'testimonials.t2Content': 'Después de años de trabajar con asesores bancarios, finalmente encontré a alguien que realmente pone mis intereses primero. Su enfoque educativo es invaluable.',
      'testimonials.t3Name': 'Ana Luisa Rodríguez',
      'testimonials.t3Role': 'Arquitecta',
      'testimonials.t3Content': 'Lo que más valoro es la paciencia y claridad con la que explica todo. Ahora mi esposo y yo tenemos un plan claro para nuestro retiro y la educación de nuestros hijos.',
      
      // FAQ
      'faq.title': 'Preguntas Frecuentes',
      'faq.subtitle': 'Resolvemos las dudas más comunes sobre nuestros servicios',
      'faq.q1': '¿Cómo funciona una primera conversación con Gregorio?',
      'faq.q2': '¿La primera conversación tiene algún costo?',
      'faq.q3': '¿Trabajas con personas en Canadá?',
      'faq.q4': '¿Trabajas con personas en Estados Unidos?',
      'faq.q5': '¿Qué tipo de servicios ofreces?',
      'faq.q6': '¿Cómo puedo saber qué opción es adecuada para mí?',
      'faq.q7': '¿Puedo recibir orientación si apenas estoy comenzando a organizar mis finanzas?',
      'faq.q8': '¿Qué diferencia existe entre ahorrar e invertir?',
      'faq.q9': '¿Cómo puedo prepararme para el retiro?',
      'faq.q10': '¿Qué significa construir resiliencia financiera?',
      'faq.a1': 'La primera conversación es un espacio para conocernos y entender tu situación actual. Escucho tus metas, preocupaciones y preguntas. A partir de ahí, te explico cómo puedo ayudarte y qué opciones existen para tu caso específico. Es una plática sin compromiso, centrada en entender tus necesidades.',
      'faq.a2': 'No, la primera conversación es completamente gratuita. Creo que es importante que nos conozcamos y que tú puedas evaluar si mi enfoque es adecuado para ti, sin ninguna presión o compromiso económico.',
      'faq.a3': 'Sí, trabajo con personas y familias en Canadá. Cuento con certificaciones en British Columbia, Alberta y Ontario, lo que me permite asesorar con conocimiento de las regulaciones y opciones disponibles en cada provincia.',
      'faq.a4': 'Sí, trabajo con personas y familias en Estados Unidos. Entiendo las particularidades del sistema financiero estadounidense y puedo orientarte sobre las opciones disponibles para residentes en EE. UU.',
      'faq.a5': 'Ofrezco servicios de planeación financiera integral: seguros de vida y gastos médicos, administración de inversiones, planeación para el retiro, estrategias de protección patrimonial, asesoría familiar y educación financiera. Cada servicio está diseñado para acompañarte en diferentes etapas de tu vida financiera.',
      'faq.a6': 'A través de nuestra conversación inicial, evaluamos juntos tu situación, metas y perfil. No se trata de una solución única, sino de encontrar la estrategia que mejor se adapte a tus circunstancias específicas. Mi rol es explicarte las opciones con claridad para que puedas tomar decisiones informadas.',
      'faq.a7': 'Absolutamente. De hecho, es uno de los mejores momentos para comenzar. La educación financiera y la planeación temprana son las herramientas más poderosas para construir un futuro financiero sólido. Te ayudo a organizar tus finanzas desde cero, estableciendo bases firmes.',
      'faq.a8': 'Ahorrar es guardar dinero para metas a corto plazo o emergencias, generalmente en instrumentos de bajo riesgo. Invertir es hacer crecer tu dinero a largo plazo, asumiendo cierto nivel de riesgo controlado para obtener rendimientos que superen la inflación. Ambos son complementarios y necesarios en una estrategia financiera saludable.',
      'faq.a9': 'La preparación para el retiro comienza con entender cuánto necesitarás y cuándo. Desarrollamos una estrategia que incluye ahorro sistemático, inversiones adecuadas a tu horizonte de tiempo, y revisión periódica de tu progreso. Nunca es demasiado temprano ni demasiado tarde para comenzar.',
      'faq.a10': 'Construir resiliencia financiera significa desarrollar la capacidad de resistir y recuperarte de imprevistos económicos. Incluye tener un fondo de emergencia, diversificar tus ingresos e inversiones, contar con protección adecuada, y mantener una mentalidad educativa sobre el dinero. Es tu capacidad de mantener la estabilidad financiera ante cualquier circunstancia.',
      'faq.ctaText': '¿Listo para conversar sobre tu futuro financiero?',
      
      // Resources
      'resources.badge': 'Recursos',
      'resources.title': 'Aprende y fortalece tu conocimiento financiero',
      'resources.subtitle': 'Compartir conocimiento es una parte importante de mi trabajo. Aquí encontrarás recursos diseñados para ayudarte a comprender mejor tus opciones financieras y tomar decisiones con mayor confianza.',
      'resources.card1Title': 'Educación financiera para familias',
      'resources.card1Desc': 'Herramientas y conceptos esenciales para tomar decisiones financieras informadas en familia.',
      'resources.card2Title': 'Construyendo resiliencia financiera',
      'resources.card2Desc': 'Estrategias prácticas para proteger tu patrimonio y enfrentar imprevistos con confianza.',
      'resources.card3Title': 'Cómo acercarte a tu independencia financiera',
      'resources.card3Desc': 'Pasos concretos para alcanzar tu número de independencia económica y vivir con tranquilidad.',
      'resources.learnMore': 'Próximamente',
      'resources.note': 'Próximamente más recursos educativos.',
      
      // Contact
      'contact.title': 'Contáctanos',
      'contact.subtitle': 'Estamos listos para ayudarte a alcanzar tus metas financieras',
      'contact.infoTitle': '¿Listo para conversar sobre tu futuro financiero?',
      'contact.infoDesc': 'Estoy aquí para ayudarte a entender tus opciones y construir una estrategia alineada con tus objetivos.',
      'contact.formIntro': 'Completa este formulario y conversemos sobre tus objetivos financieros. Mientras más información compartas, mejor podré orientarte.',
      'contact.primaryInterest': '¿Cuál es tu principal interés?',
      'contact.primaryInterestSelect': 'Selecciona una opción',
      'contact.interest.protection': 'Protección familiar',
      'contact.interest.investments': 'Inversiones',
      'contact.interest.retirement': 'Planeación para el retiro',
      'contact.interest.education': 'Educación financiera',
      'contact.interest.wealth': 'Construcción de patrimonio',
      'contact.location': '¿Dónde te encuentras?',
      'contact.locationSelect': 'Selecciona una opción',
      'contact.location.canada': 'Canadá',
      'contact.location.usa': 'Estados Unidos',
      'contact.location.mexico': 'México',
      'contact.location.other': 'Otro',
      'contact.successMessage': 'Gracias por contactarme. Revisaré tu información y me pondré en contacto contigo lo antes posible.',
      'contact.name': 'Nombre completo',
      'contact.namePlaceholder': 'Tu nombre',
      'contact.email': 'Correo electrónico',
      'contact.emailPlaceholder': 'tu@correo.com',
      'contact.phone': 'Teléfono',
      'contact.phonePlaceholder': '55 1234 5678',
      'contact.area': 'Área de interés',
      'contact.areaSelect': 'Selecciona una opción',
      'contact.area.insurance': 'Seguros',
      'contact.area.investments': 'Inversiones',
      'contact.area.retirement': 'Retiro',
      'contact.area.planning': 'Planeación financiera',
      'contact.area.protection': 'Protección patrimonial',
      'contact.area.other': 'Otro',
      'contact.message': 'Mensaje',
      'contact.messagePlaceholder': 'Cuéntanos sobre tus objetivos financieros...',
      'contact.submit': 'Enviar mensaje',
      'contact.mexico': 'México / WhatsApp',
      'contact.canada': 'Canadá (llamadas y mensajes)',
      'contact.whatsapp': 'Enviar WhatsApp',
      'contact.call': 'Llamar',
      'contact.floatingWhatsapp': '¿Preguntas? ¡Hablemos!',
      
      // Footer
      'footer.description': 'Educación financiera y asesoría humana para proteger y hacer crecer tu patrimonio.',
      'footer.services': 'Servicios',
      'footer.company': 'Empresa',
      'footer.legal': 'Legal',
      'footer.privacy': 'Aviso de privacidad',
      'footer.terms': 'Términos y condiciones',
      'footer.cookies': 'Política de cookies',
      'footer.rights': 'Todos los derechos reservados.',
      'footer.disclaimer': 'Servicios financieros proporcionados de manera independiente.',
      'footer.email': 'contacto@gregorolenro.com',
      'contact.office': 'Oficina',
      'contact.officeValue': 'Ciudad de México, México',
      'contact.hours': 'Horario',
      'contact.hoursValue': 'Lun - Vie: 9:00 AM - 6:00 PM',
      'contact.whatsappMessage': 'Hola Gregorio, visité tu sitio web y me gustaría obtener más información sobre tus servicios.',
    },
    en: {
      // Header
      'header.home': 'Home',
      'header.about': 'About Me',
      'header.podcast': 'Podcast',
      'header.services': 'Services',
      'header.process': 'Process',
      'header.resources': 'Resources',
      'header.testimonials': 'Testimonials',
      'header.faq': 'FAQ',
      'header.contact': 'Contact',
      'header.cta': 'Schedule a Consultation',
      
      // Hero
      'hero.badge': 'Personal Financial Advisor',
      'hero.title1': 'Your ally to',
      'hero.highlight': 'protect and grow',
      'hero.title2': 'your family wealth.',
      'hero.description': 'I accompany you on your journey toward financial freedom with an educational, transparent, and 100% personalized approach. Because I believe the best decisions are made with knowledge and trust.',
      'hero.cta': 'Schedule a Consultation',
      'hero.services': 'View My Services',
      'hero.clients': 'Satisfied Clients',
      'hero.experience': 'International Advisory',
      'hero.commitment': 'Commitment',
      'hero.visualName': 'Gregorio Leñero',
      'hero.visualTitle': 'Certified Financial Advisor',
      'hero.visualBadge': 'Certified',
      'hero.floatCard1': 'Wealth Growth',
      'hero.floatCard2': 'Total Protection',
      'hero.floatCard3': 'Clear Goals',
      
      // About Section
      'about.badge': 'About Me',
      'about.title': 'Building financial resilience with education and human support.',
      'about.subtitle': 'Financial Advisor in Canada and the US.',
      'about.subtitleDesc': 'I help people, families and businesses build financial resilience and reach their financial independence number.',
      'about.intro': 'I\'m Gregorio Leñero, a financial advisor with a clear mission: to help you build financial resilience and achieve your economic independence. My approach goes beyond numbers; I firmly believe that every financial decision should be aligned with your values, dreams, and life goals.',
      'about.bio': 'With years of experience advising families and businesses across North America, I\'ve developed a methodology centered on financial education and human support. My goal is to empower you with the knowledge and tools needed to make smart decisions, protect what you\'ve built, and grow your wealth with confidence.',
      'about.mission': 'My mission is simple: empower you with the knowledge and tools needed to make smart financial decisions, protect what you\'ve built, and grow your wealth with confidence.',
      'about.approachTitle': 'My Approach',
      'about.approachText': 'I believe the most important financial decisions in life should be made with clarity, education, and human support. My goal is to help you understand your options and build a financial strategy aligned with your personal, family, or business goals.',
      'about.certificationsTitle': 'Certifications',
      'about.certificationsText': 'Gregorio Leñero holds certifications in British Columbia, Alberta, and Ontario.',
      'about.certification': 'Certified Advisor',
      'about.certificationDesc': 'Certified in British Columbia, Alberta, and Ontario.',
      'about.experience': 'International Track Record',
      'about.experienceDesc': 'Proven experience helping families across North America.',
      'about.families': '500+ Families',
      'about.familiesDesc': 'Trust me for their financial peace of mind.',
      'about.approach': 'Human Approach',
      'about.approachDesc': 'Every client is unique, and my advisory adapts to your needs.',
      
      // Services
      'services.title': 'Our Services',
      'services.subtitle': 'Comprehensive financial solutions designed for every stage of your life',
      'services.insurance': 'Insurance',
      'services.insurance.desc': 'We help you protect what you love most with life, medical, and wealth insurance solutions.',
      'services.investments': 'Investments',
      'services.investments.desc': 'We manage your investment portfolio with a professional and diversified approach.',
      'services.retirement': 'Retirement',
      'services.retirement.desc': 'We design personalized strategies for you to enjoy your retirement with financial peace of mind.',
      'services.planning': 'Financial Planning',
      'services.planning.desc': 'We provide you with the tools and knowledge to make informed financial decisions.',
      'services.protection': 'Wealth Protection',
      'services.protection.desc': 'We protect your wealth through legal and financial strategies.',
      'services.family': 'Family Advisory',
      'services.family.desc': 'We work with families to align financial goals and create a solid legacy.',
      
      // Philosophy
      'philosophy.badge': 'My Philosophy',
      'philosophy.title': 'Behind every number, there\'s a person',
      'philosophy.description': 'I believe financial advisory goes beyond numbers and charts. It\'s about understanding your dreams, concerns, and goals. That\'s why I put people at the center of everything I do.',
      'philosophy.f1': '100% personalized attention without rush',
      'philosophy.f2': 'Clear explanations, no confusing jargon',
      'philosophy.f3': 'Support at every stage of your financial life',
      'philosophy.f4': 'Total transparency in recommendations and costs',
      'philosophy.f5': 'Long-term relationship, not one-time sale',
      
      // Process
      'process.title': 'Our Process',
      'process.subtitle': 'A clear and structured path toward your financial goals',
      'process.step1': 'Initial Conversation',
      'process.step1.desc': 'We get to know and understand your current situation, your goals and financial concerns.',
      'process.step2': 'Understanding Objectives',
      'process.step2.desc': 'We thoroughly analyze your needs, risk profile, and long-term expectations.',
      'process.step3': 'Personalized Options',
      'process.step3.desc': 'We design a proposal specifically adapted to your situation and objectives.',
      'process.step4': 'Clear Explanation',
      'process.step4.desc': 'We explain every detail of the strategy, resolving all your questions without rush.',
      'process.step5': 'Implementation',
      'process.step5.desc': 'We put the plan into action, accompanying you at every step of the process.',
      'process.step6': 'Continuous Support',
      'process.step6.desc': 'We provide constant follow-up and adjust the strategy as needed.',
      
      // Trust
      'trust.title': 'Trust and Security',
      'trust.subtitle': 'Your wealth in the hands of certified professionals',
      'trust.t1': 'Canadian Certifications',
      'trust.t1.desc': 'Gregorio Leñero holds certifications in British Columbia, Alberta, and Ontario, supporting his ability to advise clients across different Canadian provinces.',
      'trust.t2': 'International Track Record',
      'trust.t2.desc': 'Proven experience helping families across North America.',
      'trust.t3': 'Solid Partnerships',
      'trust.t3.desc': 'We work with the most recognized financial institutions.',
      'trust.t4': '500+ Families',
      'trust.t4.desc': 'More than 500 families trust us for their financial peace of mind.',
      
      // Testimonials
      'testimonials.title': 'What Our Clients Say',
      'testimonials.subtitle': 'Real stories from people who trusted us',
      'testimonials.t1Name': 'María González',
      'testimonials.t1Role': 'Entrepreneur',
      'testimonials.t1Content': 'Gregorio completely changed my perspective on money. Thanks to his advisory, I managed to protect my family and grow my investments intelligently.',
      'testimonials.t2Name': 'Carlos Hernández',
      'testimonials.t2Role': 'Physician',
      'testimonials.t2Content': 'After years of working with bank advisors, I finally found someone who truly puts my interests first. His educational approach is invaluable.',
      'testimonials.t3Name': 'Ana Luisa Rodríguez',
      'testimonials.t3Role': 'Architect',
      'testimonials.t3Content': 'What I value most is the patience and clarity with which he explains everything. Now my husband and I have a clear plan for our retirement and our children\'s education.',
      
      // FAQ
      'faq.title': 'Frequently Asked Questions',
      'faq.subtitle': 'We answer the most common questions about our services',
      'faq.q1': 'How does a first conversation with Gregorio work?',
      'faq.q2': 'Is the first conversation free?',
      'faq.q3': 'Do you work with clients in Canada?',
      'faq.q4': 'Do you work with clients in the United States?',
      'faq.q5': 'What services do you offer?',
      'faq.q6': 'How can I know which option is right for me?',
      'faq.q7': 'Can I receive guidance if I am just starting to organize my finances?',
      'faq.q8': 'What is the difference between saving and investing?',
      'faq.q9': 'How can I prepare for retirement?',
      'faq.q10': 'What does financial resilience mean?',
      'faq.a1': 'The first conversation is a space to get to know each other and understand your current situation. I listen to your goals, concerns, and questions. From there, I explain how I can help and what options exist for your specific case. It\'s a no-obligation conversation focused on understanding your needs.',
      'faq.a2': 'No, the first conversation is completely free. I believe it\'s important that we get to know each other and that you can evaluate if my approach is right for you, without any pressure or financial commitment.',
      'faq.a3': 'Yes, I work with people and families in Canada. I hold certifications in British Columbia, Alberta, and Ontario, which allows me to advise with knowledge of the regulations and options available in each province.',
      'faq.a4': 'Yes, I work with people and families in the United States. I understand the particularities of the US financial system and can guide you on the options available to US residents.',
      'faq.a5': 'I offer comprehensive financial planning services: life and medical insurance, investment management, retirement planning, wealth protection strategies, family advisory, and financial education. Each service is designed to accompany you through different stages of your financial life.',
      'faq.a6': 'Through our initial conversation, we evaluate your situation, goals, and profile together. It\'s not about a one-size-fits-all solution, but about finding the strategy that best fits your specific circumstances. My role is to explain the options clearly so you can make informed decisions.',
      'faq.a7': 'Absolutely. In fact, it\'s one of the best times to start. Financial education and early planning are the most powerful tools for building a solid financial future. I help you organize your finances from scratch, establishing firm foundations.',
      'faq.a8': 'Saving is setting aside money for short-term goals or emergencies, typically in low-risk instruments. Investing is growing your money over the long term, assuming a controlled level of risk to achieve returns that outpace inflation. Both are complementary and necessary in a healthy financial strategy.',
      'faq.a9': 'Retirement preparation begins with understanding how much you\'ll need and when. We develop a strategy that includes systematic saving, investments appropriate to your time horizon, and periodic progress reviews. It\'s never too early or too late to start.',
      'faq.a10': 'Building financial resilience means developing the ability to withstand and recover from economic unexpected events. It includes having an emergency fund, diversifying your income and investments, having adequate protection, and maintaining an educational mindset about money. It\'s your capacity to maintain financial stability under any circumstances.',
      'faq.ctaText': 'Ready to talk about your financial future?',
      
      // Resources
      'resources.badge': 'Resources',
      'resources.title': 'Learn and strengthen your financial knowledge',
      'resources.subtitle': 'Sharing knowledge is an important part of my work. Here you will find resources designed to help you better understand your financial options and make decisions with greater confidence.',
      'resources.card1Title': 'Financial education for families',
      'resources.card1Desc': 'Essential tools and concepts to make informed financial decisions as a family.',
      'resources.card2Title': 'Building financial resilience',
      'resources.card2Desc': 'Practical strategies to protect your wealth and face unexpected events with confidence.',
      'resources.card3Title': 'Getting closer to financial independence',
      'resources.card3Desc': 'Concrete steps to reach your financial independence number and live with peace of mind.',
      'resources.learnMore': 'Coming Soon',
      'resources.note': 'More educational resources coming soon.',
      
      // Contact
      'contact.title': 'Contact Us',
      'contact.subtitle': 'We\'re ready to help you achieve your financial goals',
      'contact.infoTitle': 'Ready to talk about your financial future?',
      'contact.infoDesc': 'I\'m here to help you understand your options and build a strategy aligned with your goals.',
      'contact.formIntro': 'Complete this form and let\'s talk about your financial goals. The more information you share, the better I can guide you.',
      'contact.primaryInterest': 'What is your primary interest?',
      'contact.primaryInterestSelect': 'Select an option',
      'contact.interest.protection': 'Family protection',
      'contact.interest.investments': 'Investments',
      'contact.interest.retirement': 'Retirement planning',
      'contact.interest.education': 'Financial education',
      'contact.interest.wealth': 'Wealth building',
      'contact.location': 'Where are you located?',
      'contact.locationSelect': 'Select an option',
      'contact.location.canada': 'Canada',
      'contact.location.usa': 'United States',
      'contact.location.mexico': 'Mexico',
      'contact.location.other': 'Other',
      'contact.successMessage': 'Thank you for reaching out. I will review your information and contact you as soon as possible.',
      'contact.name': 'Full Name',
      'contact.namePlaceholder': 'Your name',
      'contact.email': 'Email Address',
      'contact.emailPlaceholder': 'your@email.com',
      'contact.phone': 'Phone',
      'contact.phonePlaceholder': '55 1234 5678',
      'contact.area': 'Area of Interest',
      'contact.areaSelect': 'Select an option',
      'contact.area.insurance': 'Insurance',
      'contact.area.investments': 'Investments',
      'contact.area.retirement': 'Retirement',
      'contact.area.planning': 'Financial Planning',
      'contact.area.protection': 'Wealth Protection',
      'contact.area.other': 'Other',
      'contact.message': 'Message',
      'contact.messagePlaceholder': 'Tell us about your financial goals...',
      'contact.submit': 'Send Message',
      'contact.mexico': 'Mexico / WhatsApp',
      'contact.canada': 'Canada (calls and texts)',
      'contact.whatsapp': 'Send WhatsApp',
      'contact.call': 'Call',
      'contact.floatingWhatsapp': 'Questions? Let\'s talk!',
      
      // Footer
      'footer.description': 'Financial education and human advisory to protect and grow your wealth.',
      'footer.services': 'Services',
      'footer.company': 'Company',
      'footer.legal': 'Legal',
      'footer.privacy': 'Privacy Notice',
      'footer.terms': 'Terms and Conditions',
      'footer.cookies': 'Cookie Policy',
      'footer.rights': 'All rights reserved.',
      'footer.disclaimer': 'Financial services provided independently.',
      'footer.email': 'contacto@gregorolenro.com',
      'contact.office': 'Office',
      'contact.officeValue': 'Mexico City, Mexico',
      'contact.hours': 'Hours',
      'contact.hoursValue': 'Mon - Fri: 9:00 AM - 6:00 PM',
      'contact.whatsappMessage': 'Hello Gregorio, I visited your website and would like to get more information about your services.',
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;